
# This is a basic workflow to help you get started with Actions



name: CI



# Controls when the action will run. Triggers the workflow on push or pull request

# events but only for the master branch

on:

  push:

    branches: [ master ]

  pull_request:

    branches: [ master ]



jobs:

  gradle:

    strategy:

      matrix:

        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:

      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1

        with:

          java-version: 11

      # do not forget `git update-index --chmod=+x gradlew` to fix permission before !

      - uses: eskatos/gradle-command-action@v1

        with:

          arguments: test
